openapi: '3.0.3'

info:
  version: 0.1.0
  title: Perfect Gift Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /dummy:
    get:
      description: Dummy Endpoint
      responses:
        200:
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DummyResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    DummyResponse:
      required:
        - message
      properties:
        message:
          type: string

    User:
      description: A user and its data
      type: array
      items:
        type: object
        properties:
          firstname:
            type: string
          lastname:
            type: string
          useremail:
            type: string
            format: email
          username:
            type: string
          userpassword:
            type: string
          avatarurl:
            type: string
          showavatar:
            type: boolean
        required:
          - firstname
          - lastname
          - useremail
          - username

    QuestionnaireResponses:
      description: User's responses to interest questionnaire
      type: array
      items:
        type: object
        properties:
          username:
            type: string
          outdooractivity:
            type: string
          place:
            type: string
          store:
            type: string
          musicgenre:
            type: string
          musician:
            type: string
          band:
            type: string
          indooractivity:
            type: string
          movietvshow:
            type: string
          videogame:
            type: string
          sport:
            type: string
          sportteam:
            type: string
          exercise:
            type: string
        required:
          - username